services:
  bot:
    build: .
    container_name: yt-bot
    command: python -u app/bot.py
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/downloads
      - ./credentials:/credentials
    depends_on:
      - redis

  worker:
    build: .
    container_name: yt-worker
    command: python -u app/worker.py
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/downloads
      - ./credentials:/credentials
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: yt-redis
    restart: unless-stopped